# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easy-gtalk-bot}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Vartanov"]
  s.date = %q{2010-06-28}
  s.description = %q{easy-gtalk-bot lets you create and run GTalk bot in 5 minutes}
  s.email = %q{dan@vartanov.net}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION.yml",
     "easy-gtalk-bot.gemspec",
     "examples/the_simplest_bot.rb",
     "lib/easy-gtalk-bot.rb"
  ]
  s.homepage = %q{http://github.com/DanielVartanov/easy-gtalk-bot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A very easy tool for creating Google Talk bots}
  s.test_files = [
    "examples/the_simplest_bot.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xmpp4r>, [">= 0.5"])
    else
      s.add_dependency(%q<xmpp4r>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<xmpp4r>, [">= 0.5"])
  end
end

